name: Update File Time Info

on:
  push:
    branches:
      - main

jobs:
  update_file_time_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configure Git and date
        run: |
          git config user.name "vercel"
          git config user.email "vercel[bot]@users.noreply.github.com"
          echo "DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: Update files with commit info
        run: |
          for file in Proxy/**/*; do
            [[ -f "$file" ]] || continue

            if [[ "$file" == *.mrs ]]; then
              echo "跳过 $file"
              continue
            fi

            if git diff --quiet HEAD^ HEAD -- "$file"; then
              echo "$file has no changes in the last commit."
              continue
            fi

            sed -i -E "s/^# Updated: .*/# Updated: $DATE/" "$file"
          done

      - name: Commit and push changes
        run: |
          git add Proxy/**/*
          git commit --amend --reset-author -m "$DATE"
          git push --force origin main

      - name: Translate job status to Chinese
        run: |
          case "${{ job.status }}" in
            success) translated_status="成功" ;;
            failure) translated_status="失败" ;;
            cancelled) translated_status="取消" ;;
            *) translated_status="未知" ;;
          esac
          echo "translated_status=$translated_status" >> $GITHUB_ENV

      - name: Notify job status
        if: always()
        run: |
          curl -X "POST" "${{ secrets.BARK_KEY }}" \
             -H 'Content-Type: application/json; charset=utf-8' \
             -d '{
                    "body": "${{ github.repository }}于${{ env.DATE }}运行${{ env.translated_status }}",
                    "title": "Github Actions",
                    "badge": 1,
                    "sound": "multiwayinvitation.caf",
                    "icon": "https://i.theojs.net/cdn-cgi/image/format=png/logo/vercel-light.webp",
                    "group": "Github Actions"
                  }'
